# Generated by Django 3.2 on 2021-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_discount_expiry'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logo', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='products.Product', verbose_name='Избранное'),
        ),
    ]
