# Generated by Django 3.2.4 on 2021-06-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='prefix',
            field=models.CharField(blank=True, default='+38', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('all', 'Вся Украина'), ('karkov', 'Харьков'), ('kiev', 'Киев'), ('dnepr', 'Днепр'), ('sumy', 'Суммы'), ('ternopol', 'Тернополь'), ('vinica', 'Винница'), ('lvov', 'Львов')], default='all', max_length=30),
        ),
    ]
