# Generated by Django 3.2.4 on 2021-06-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210604_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='users.profile'),
        ),
    ]
