# Generated by Django 3.2 on 2021-05-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
    ]
