# Generated by Django 3.2 on 2021-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('0', 'Все'), ('1', 'Харьков'), ('2', 'Киев'), ('3', 'Днепр'), ('4', 'Суммы'), ('5', 'Тернополь'), ('6', 'Винница'), ('7', 'Львов'), ('8', 'Запоорожье'), ('9', 'Ровно'), ('10', 'Полтава'), ('11', 'Донецк'), ('12', 'Ивано-Франковск'), ('13', 'Харьков'), ('14', 'Киев'), ('15', 'Днепр')], max_length=50, null=True, verbose_name='Город'),
        ),
    ]
