# Generated by Django 3.2.3 on 2021-05-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[(0, 'Вся Украина'), (1, 'Харьков'), (2, 'Киев'), (3, 'Днепр'), (4, 'Суммы'), (5, 'Тернополь'), (6, 'Винница'), (7, 'Львов'), (8, 'Запоорожье'), (9, 'Ровно'), (10, 'Полтава'), (11, 'Донецк'), (12, 'Ивано-Франковск'), (13, 'Харьков'), (14, 'Киев'), (15, 'Днепр')], max_length=50, null=True, verbose_name='Город'),
        ),
    ]
