# Generated by Django 3.2.3 on 2021-05-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210521_0044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPhone',
            new_name='Phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
