# Generated by Django 3.2.3 on 2021-05-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='social',
            field=models.CharField(choices=[(1, 'Telegram'), (2, 'Viber'), (3, 'Whatsup'), (4, 'Facebook')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
