# Generated by Django 3.2.3 on 2021-05-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_phone_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='users.profile'),
        ),
    ]
