# Generated by Django 3.2 on 2021-05-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210428_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
