# Generated by Django 3.2.3 on 2021-05-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetype', models.CharField(choices=[(0, 'About'), (1, 'Rules'), (2, 'For sallers')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='infopages_img')),
                ('video', models.URLField(blank=True, null=True)),
                ('first_title', models.CharField(max_length=100)),
                ('first_text', models.TextField(max_length=200)),
                ('second_title', models.CharField(blank=True, max_length=100, null=True)),
                ('second_text', models.TextField(blank=True, max_length=200, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='infopages.page')),
            ],
        ),
    ]
