# Generated by Django 3.2.3 on 2021-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[(0, 'About'), (1, 'Rules'), (2, 'For sallers')], default=0, max_length=11)),
                ('image', models.ImageField(upload_to='infopages_img')),
                ('first_title', models.CharField(max_length=100)),
                ('first_text', models.TextField(max_length=200)),
                ('second_title', models.CharField(blank=True, max_length=100, null=True)),
                ('second_text', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rule',
            name='page',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
