# Generated by Django 3.2.3 on 2021-05-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0002_auto_20210521_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetype', models.CharField(choices=[(0, 'About'), (1, 'Rules'), (2, 'For sallers')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='infoblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='infopages.page'),
        ),
    ]
