# Generated by Django 3.2.3 on 2021-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0003_auto_20210524_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoblock',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infoblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='infopages_img'),
        ),
    ]
