# Generated by Django 3.2 on 2021-05-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_options'),
        ('subscribes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribtion',
            name='contact_whith',
        ),
        migrations.AddField(
            model_name='subscribtion',
            name='use_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscribtion',
            name='use_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscribtion',
            name='use_viber',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribtion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.Category'),
        ),
    ]
