# Generated by Django 3.2 on 2021-05-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_servicefeedback_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='username',
            new_name='name',
        ),
    ]
