# Generated by Django 3.2.1 on 2021-05-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0004_auto_20210510_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribtion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscribtion',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='subscribtion',
            name='viber',
        ),
        migrations.AddField(
            model_name='subscribtion',
            name='social',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('viber', 'Viber')], default='email', max_length=10),
        ),
    ]
