# Generated by Django 3.2 on 2021-05-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0006_alter_subscribtion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='region',
            field=models.CharField(choices=[('0', 'Вся Украина'), ('1', 'Харьков'), ('2', 'Киев'), ('3', 'Днепр'), ('4', 'Суммы'), ('5', 'Тернополь'), ('6', 'Винница'), ('7', 'Львов'), ('8', 'Запоорожье'), ('9', 'Ровно'), ('10', 'Полтава'), ('11', 'Донецк'), ('12', 'Ивано-Франковск'), ('13', 'Харьков'), ('14', 'Киев'), ('15', 'Днепр')], default=0, max_length=50),
        ),
    ]
