# Generated by Django 3.2.3 on 2021-05-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0007_alter_subscribtion_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribtion',
            name='social',
        ),
        migrations.AddField(
            model_name='subscribtion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subscribtion',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscribtion',
            name='viber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
