# Generated by Django 3.2.3 on 2021-05-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0010_alter_subscribtion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribtion',
            name='region',
            field=models.CharField(choices=[('all', 'Вся Украина'), ('karkov', 'Харьков'), ('kiev', 'Киев'), ('dnepr', 'Днепр'), ('sumy', 'Суммы'), ('ternopol', 'Тернополь'), ('vinica', 'Винница'), ('lvov', 'Львов')], default='all', max_length=50),
        ),
    ]
