# Generated by Django 3.2 on 2021-05-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceFeedback',
            new_name='Feedback',
        ),
    ]
