# Generated by Django 3.2.4 on 2021-06-11 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=25)),
                ('image', models.FileField(blank=True, null=True, upload_to='social_links', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
            ],
        ),
    ]
