# Generated by Django 3.2 on 2021-05-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар/Акция', 'verbose_name_plural': 'Товары/Акции'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
