# Generated by Django 3.2 on 2021-05-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210502_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Товар/Акция', 'verbose_name_plural': 'Товары/Акции'},
        ),
    ]
