# Generated by Django 3.2.3 on 2021-05-31 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='category_img', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
