# Generated by Django 3.2 on 2021-04-16 15:22

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(default=products.models.set_discount_expiry),
        ),
    ]
