# Generated by Django 3.2 on 2021-04-23 06:40

from django.db import migrations, models
import products.models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(
                default=timezone.now, verbose_name='Дата окончания акции'),
        ),
    ]
