# Generated by Django 3.2.4 on 2021-06-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210606_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
