# Generated by Django 3.2.1 on 2021-05-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
