# Generated by Django 3.2 on 2021-05-14 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210514_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(choices=[('0', 'Вся Украина'), ('1', 'Харьков'), ('2', 'Киев'), ('3', 'Днепр'), ('4', 'Суммы'), ('5', 'Тернополь'), ('6', 'Винница'), ('7', 'Львов'), ('8', 'Запоорожье'), ('9', 'Ровно'), ('10', 'Полтава'), ('11', 'Донецк'), ('12', 'Ивано-Франковск'), ('13', 'Харьков'), ('14', 'Киев'), ('15', 'Днепр')], default=0, max_length=20, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 11, 46, 59, 765523), verbose_name='Дата окончания акции'),
        ),
    ]
