# Generated by Django 3.2.3 on 2021-05-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210514_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания акции'),
        ),
    ]
