# Generated by Django 3.2.3 on 2021-05-14 23:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_discount_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 23, 39, 46, 179245, tzinfo=utc), verbose_name='Дата окончания акции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключевые слова'),
        ),
    ]
