# Generated by Django 3.2.3 on 2021-05-14 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210515_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания акции'),
        ),
    ]
