# Generated by Django 3.2.3 on 2021-05-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_discount_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
