# Generated by Django 3.2.3 on 2021-05-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210516_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.IntegerField(default=30),
        ),
    ]
