# Generated by Django 3.2.3 on 2021-05-17 11:52

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.IntegerField(default=products.models.default_discount_expiry),
        ),
    ]
