# Generated by Django 3.2.3 on 2021-05-17 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_discount_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 15, 0, 38, 100472)),
        ),
    ]
