# Generated by Django 3.2.3 on 2021-05-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_main',
        ),
    ]
