# Generated by Django 3.2.3 on 2021-05-19 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20210519_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 19, 25, 42, 842124, tzinfo=utc)),
        ),
    ]
