# Generated by Django 3.2.3 on 2021-05-20 13:36

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_discount_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiry_date',
            field=models.DateTimeField(default=products.models.default_discount_expiry),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(choices=[('all', 'Вся Украина'), ('karkov', 'Харьков'), ('kiev', 'Киев'), ('dnepr', 'Днепр'), ('sumy', 'Суммы'), ('ternopol', 'Тернополь'), ('vinica', 'Винница'), ('lvov', 'Львов')], default='all', max_length=20),
        ),
    ]
