# Generated by Django 3.2.3 on 2021-05-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_remove_discount_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='overview',
            new_name='about',
        ),
    ]
