# Generated by Django 3.2.3 on 2021-05-24 15:10

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20210523_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(default=products.models.default_discount_expiry),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
