# Generated by Django 3.2.3 on 2021-05-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_auto_20210524_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_overview',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
